### ISSUE TITLE
Fabricator UI just straight up doesn't work

### ISSUE THREAD

**Issue by Rythian2277** [Chronowire-Studios/TUTGDevBranch#18]
![image](https://github.com/Chronowire-Studios/TUTGDevBranch/assets/26336033/283e2304-6541-4c0e-9ba9-184073e236d1)

It also doesn't reset if you reset your character to try and remove it

**Comment by ChronowireStudios** [comment]
I'm going to kms

**Comment by ChronowireStudios** [comment]
please be fixed
