### ISSUE TITLE
Tempad Error (might be the Master Tempad only, as Betas were able to use it)

### ISSUE THREAD

**Issue by ChronowireStudios** [Chronowire-Studios/TUTGDevBranch#35]
![image](https://github.com/user-attachments/assets/d1718a51-ed1b-4c9d-9826-ca79674fc3d7)

**Comment by ChronowireStudios** [comment]
@Rythian2277

**Comment by Rythian2277** [comment]
Interesting, will take a look...

**Comment by ChronowireStudios** [comment]
> Interesting, will take a look...

Beta are able to use the old model, but the only location is the one they are at, not sure if related or not

**Comment by Rythian2277** [comment]
I think its directly linked to the update to patch miss minutes since I changed a few extra aspects of the code to accommodate her patch.

**Comment by ChronowireStudios** [comment]
gg

**Comment by Rythian2277** [comment]
very very weird

the code has no errors when running through tests, guess i have to do some ingame debugging (yay!)

**Comment by Rythian2277** [comment]
am a biiig biiig idiot, it's trying to pull data from a datastore that doesn't exist. fixed.

**Comment by ChronowireStudios** [comment]
Am I good to close?

**Comment by Rythian2277** [comment]
yes

**Comment by Rythian2277** [comment]
was literally fixed by a single `or {}` lmao

**Comment by ChronowireStudios** [comment]
![image](https://github.com/user-attachments/assets/b3ce5012-270d-46af-a20d-24a934490293)
@Rythian2277

**Comment by Rythian2277** [comment]
Hisssssssz

**Comment by ChronowireStudios** [comment]
hurray
