### ISSUE TITLE
tempad unavailable on mobile

### ISSUE THREAD

**Issue by Av3rnus** [Chronowire-Studios/TUTGDevBranch#46]

**Comment by Rythian2277** [comment]
This empty issue is very helpful at identifying the problem...

**Comment by Av3rnus** [comment]
> This empty issue is very helpful at identifying the problem...

whenever i try and open a timedoor it just says "unavailable"

**Comment by Rythian2277** [comment]
Issue resolved, you have to use the "Options" entry first to select a destination. This then enables the Timedoor's "Run Program". "Clear Cache" can then be used to close the open Timedoor.
