### ISSUE TITLE
Add a "QuestItem" attribute to some of the item buttons in the Fabricator, so that it can have checks for items such as K9 and the Mask from Relic of the Tombraider

### ISSUE THREAD

**Issue by ChronowireStudios** [Chronowire-Studios/TUTGDevBranch#9]

**Comment by ChronowireStudios** [comment]
said fuck it, hard coded it in to disable the mask and K9 unless the player is at the appropriate queststage (instead of using attributes to mark it as a "Quest" item)

**Comment by Rythian2277** [comment]
Bad futureproofing :(

**Comment by ChronowireStudios** [comment]
> Bad futureproofing :(

Very well, I went in and adjusted it haha
